apiVersion: v1
kind: ConfigMap
metadata:
  name: attribute-service-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDISSON_HOST: "redis"
  REDISSON_PORT: "6379"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://attribute-db:5435/stroy1click"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_FLYWAY_URL: "jdbc:postgresql://attribute-db:5435/stroy1click"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

  SERVER_ADDRESS: "0.0.0.0"

  OTEL_SERVICE_NAME: "attribute-service"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORT_INTERVAL: "5000"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"