apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3
type: Opaque
stringData:
  TEMPO_STORAGE_TRACE_S3_ACCESS_KEY: "b0a085fad6914c2abd49b762ee2263e2"
  TEMPO_STORAGE_TRACE_S3_SECRET_KEY: "2bd487564bb54e9a8231bb3944108971"