apiVersion: v1
kind: ConfigMap
metadata:
  name: jwt-validator-service-config
data:
  SPRING_PROFILES_ACTIVE: "prod"

  SERVER_ADDRESS: "0.0.0.0"

  OTEL_SERVICE_NAME: "jwt-validator-service"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORT_INTERVAL: "5000"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"