apiVersion: v1
kind: Service
metadata:
  name: jwt-validator-service
spec:
  selector:
    app: jwt-validator-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
  type: ClusterIP
  