apiVersion: v1
kind: ConfigMap
metadata:
  name: confirmation-code-service-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: "prod"
  REDISSON_HOST: "redis"
  REDISSON_PORT: "6379"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://confirmation-code-db:5436/stroy1click"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_FLYWAY_URL: "jdbc:postgresql://confirmation-code-db:5436/stroy1click"
  SPRING_FLYWAY_USER: "postgres"
  SPRING_FLYWAY_PASSWORD: "password"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

  URL_USER: "http://user-service:8080/api/v1/users"
  URL_AUTH: "http://auth-service:9090/api/v1/auth"
  URL_EMAIL: "http://email-service:5050/api/v1/emails"

  SERVER_ADDRESS: "0.0.0.0"

  OTEL_SERVICE_NAME: "confirmation-code-service"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORT_INTERVAL: "5000"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"