apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      name: search-service
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: stroy1click/search:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 4045
              protocol: TCP

      restartPolicy: Always
      