apiVersion: apps/v1
kind: Deployment
metadata:
  name: attribute-deployment
  labels:
    app: attribute-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attribute-service
  template:
    metadata:
      name: attribute-service
      labels:
        app: attribute-service
    spec:
      containers:
        - name: attribute-service
          image: stroy1click/attribute:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 4040
              protocol: TCP
          envFrom:
            - configMapRef:
                name: attribute-service-config
          livenessProbe:
            httpGet:
              port: 4040
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3

      restartPolicy: Always
      