apiVersion: v1
kind: Service
metadata:
  name: attribute-service
  namespace: dev
spec:
  selector:
    app: attribute-service
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30040
  type: NodePort
  