apiVersion: apps/v1
kind: Deployment
metadata:
  name: confirmation-code-deployment
  labels:
    app: confirmation-code-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: confirmation-code-service
  template:
    metadata:
      name: confirmation-code-service
      labels:
        app: confirmation-code-service
    spec:
      containers:
        - name: confirmation-code-service
          image: stroy1click/confirmation:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 6060
              protocol: TCP
          envFrom:
            - configMapRef:
                name: confirmation-code-service-config
            - secretRef:
                name: auth-secret
          livenessProbe:
            httpGet:
              port: 6060
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 6060
              path: /actuator/health
            initialDelaySeconds: 240
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        size: large
      