apiVersion: v1
kind: Service
metadata:
  name: confirmation-code-service
spec:
  selector:
    app: confirmation-code-service
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
  type: ClusterIP
  