apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: dev
spec:
  selector:
    app: otel-collector
  ports:
    - name: http
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: grpc
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: prom-exp
      port: 9464
      targetPort: 9464
  type: ClusterIP